baseurl: /
languageCode: en-us
title: erg home
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:slug/
menu:
  main:
    - name: about
      url: /about/
      weight: 1
    - name: testing
      url: /testing/
      weight: 2
    - name: location
      url: /location/
      weight: 3
    - name: our team
      url: /our-team/
      weight: 4
    - name: GitHub
      url: https://github.com/jtkulas
      weight: 5
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Webpage for erg consultancy focusing on employee engagement.
  favicon: erg5.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: erg5
    height: 50
    url: erg5.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
