baseurl: "https://ergreports.com/"
languageCode: en-us
title: erg home
theme: hugo-lithium
googleAnalytics: 'G-RK7D4E54FE'
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  content: /:slug/
menu:
  main:
    - name: Workforce Engagement
      url: /Workforce Engagement/
      weight: 2
    - name: About Us
      url: /our-team/
      weight: 5      
    - name: Assessments Auditing
      url: /testing/
      weight: 3
    - name: Process Automation
      url: /Automation/
      weight: 4
    - name: Resources
      url: /references/
      weight: 6
#    - name: GitHub
#      url: https://github.com/jtkulas/erg
#      weight: 7
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Webpage for eRg consultancy.
  favicon: erg7.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: erghome
    height: 50
    url: erg2.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
