baseurl: "https://ergweb.netlify.app/"
languageCode: en-us
title: erg home
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  content: /:slug/
menu:
  main:
    - name: testing
      url: /testing/
      weight: 3
    - name: location
      url: /location/
      weight: 4
    - name: our team
      url: /our-team/
      weight: 5
    - name: GitHub
      url: https://github.com/jtkulas/erg
      weight: 6
    - name: products
      url: /product/
      weight: 2
    - name: phantazee
      url: /phantazee/
      weight: 7
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Webpage for erg consultancy focusing on employee engagement.
  favicon: erg2.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: erghome
    height: 50
    url: erg2.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
